"""
Constantes pour l'application - Indicatifs pays et autres valeurs fixes
"""

# Liste des indicatifs pays avec leur nom
# Format: (indicatif, nom du pays)
COUNTRY_CODES = [
    ("+1", "États-Unis / Canada"),
    ("+7", "Russie"),
    ("+20", "Égypte"),
    ("+27", "Afrique du Sud"),
    ("+30", "Grèce"),
    ("+31", "Pays-Bas"),
    ("+32", "Belgique"),
    ("+33", "France"),
    ("+34", "Espagne"),
    ("+36", "Hongrie"),
    ("+39", "Italie"),
    ("+40", "Roumanie"),
    ("+41", "Suisse"),
    ("+43", "Autriche"),
    ("+44", "Royaume-Uni"),
    ("+45", "Danemark"),
    ("+46", "Suède"),
    ("+47", "Norvège"),
    ("+48", "Pologne"),
    ("+49", "Allemagne"),
    ("+51", "Pérou"),
    ("+52", "Mexique"),
    ("+53", "Cuba"),
    ("+54", "Argentine"),
    ("+55", "Brésil"),
    ("+56", "Chili"),
    ("+57", "Colombie"),
    ("+58", "Venezuela"),
    ("+60", "Malaisie"),
    ("+61", "Australie"),
    ("+62", "Indonésie"),
    ("+63", "Philippines"),
    ("+64", "Nouvelle-Zélande"),
    ("+65", "Singapour"),
    ("+66", "Thaïlande"),
    ("+81", "Japon"),
    ("+82", "Corée du Sud"),
    ("+84", "Vietnam"),
    ("+86", "Chine"),
    ("+90", "Turquie"),
    ("+91", "Inde"),
    ("+92", "Pakistan"),
    ("+93", "Afghanistan"),
    ("+94", "Sri Lanka"),
    ("+95", "Myanmar"),
    ("+98", "Iran"),
    ("+212", "Maroc"),
    ("+213", "Algérie"),
    ("+216", "Tunisie"),
    ("+218", "Libye"),
    ("+220", "Gambie"),
    ("+221", "Sénégal"),
    ("+222", "Mauritanie"),
    ("+223", "Mali"),
    ("+224", "Guinée"),
    ("+225", "Côte d'Ivoire"),
    ("+226", "Burkina Faso"),
    ("+227", "Niger"),
    ("+228", "Togo"),
    ("+229", "Bénin"),
    ("+230", "Maurice"),
    ("+231", "Liberia"),
    ("+232", "Sierra Leone"),
    ("+233", "Ghana"),
    ("+234", "Nigeria"),
    ("+235", "Tchad"),
    ("+236", "République centrafricaine"),
    ("+237", "Cameroun"),
    ("+238", "Cap-Vert"),
    ("+239", "São Tomé-et-Príncipe"),
    ("+240", "Guinée équatoriale"),
    ("+241", "Gabon"),
    ("+242", "République du Congo"),
    ("+243", "République démocratique du Congo"),
    ("+244", "Angola"),
    ("+245", "Guinée-Bissau"),
    ("+246", "Diego Garcia"),
    ("+247", "Ascension"),
    ("+248", "Seychelles"),
    ("+249", "Soudan"),
    ("+250", "Rwanda"),
    ("+251", "Éthiopie"),
    ("+252", "Somalie"),
    ("+253", "Djibouti"),
    ("+254", "Kenya"),
    ("+255", "Tanzanie"),
    ("+256", "Ouganda"),
    ("+257", "Burundi"),
    ("+258", "Mozambique"),
    ("+260", "Zambie"),
    ("+261", "Madagascar"),
    ("+262", "Réunion"),
    ("+263", "Zimbabwe"),
    ("+264", "Namibie"),
    ("+265", "Malawi"),
    ("+266", "Lesotho"),
    ("+267", "Botswana"),
    ("+268", "Eswatini"),
    ("+269", "Comores"),
    ("+290", "Sainte-Hélène"),
    ("+291", "Érythrée"),
    ("+297", "Aruba"),
    ("+298", "Îles Féroé"),
    ("+299", "Groenland"),
    ("+350", "Gibraltar"),
    ("+351", "Portugal"),
    ("+352", "Luxembourg"),
    ("+353", "Irlande"),
    ("+354", "Islande"),
    ("+355", "Albanie"),
    ("+356", "Malte"),
    ("+357", "Chypre"),
    ("+358", "Finlande"),
    ("+359", "Bulgarie"),
    ("+370", "Lituanie"),
    ("+371", "Lettonie"),
    ("+372", "Estonie"),
    ("+373", "Moldavie"),
    ("+374", "Arménie"),
    ("+375", "Biélorussie"),
    ("+376", "Andorre"),
    ("+377", "Monaco"),
    ("+378", "Saint-Marin"),
    ("+380", "Ukraine"),
    ("+381", "Serbie"),
    ("+382", "Monténégro"),
    ("+383", "Kosovo"),
    ("+385", "Croatie"),
    ("+386", "Slovénie"),
    ("+387", "Bosnie-Herzégovine"),
    ("+389", "Macédoine du Nord"),
    ("+420", "République tchèque"),
    ("+421", "Slovaquie"),
    ("+423", "Liechtenstein"),
    ("+500", "Îles Malouines"),
    ("+501", "Belize"),
    ("+502", "Guatemala"),
    ("+503", "Salvador"),
    ("+504", "Honduras"),
    ("+505", "Nicaragua"),
    ("+506", "Costa Rica"),
    ("+507", "Panama"),
    ("+508", "Saint-Pierre-et-Miquelon"),
    ("+509", "Haïti"),
    ("+590", "Guadeloupe"),
    ("+591", "Bolivie"),
    ("+592", "Guyana"),
    ("+593", "Équateur"),
    ("+594", "Guyane française"),
    ("+595", "Paraguay"),
    ("+596", "Martinique"),
    ("+597", "Suriname"),
    ("+598", "Uruguay"),
    ("+599", "Curaçao"),
    ("+670", "Timor oriental"),
    ("+672", "Île Norfolk"),
    ("+673", "Brunei"),
    ("+674", "Nauru"),
    ("+675", "Papouasie-Nouvelle-Guinée"),
    ("+676", "Tonga"),
    ("+677", "Îles Salomon"),
    ("+678", "Vanuatu"),
    ("+679", "Fidji"),
    ("+680", "Palaos"),
    ("+681", "Wallis-et-Futuna"),
    ("+682", "Îles Cook"),
    ("+683", "Niue"),
    ("+685", "Samoa"),
    ("+686", "Kiribati"),
    ("+687", "Nouvelle-Calédonie"),
    ("+688", "Tuvalu"),
    ("+689", "Polynésie française"),
    ("+690", "Tokelau"),
    ("+691", "Micronésie"),
    ("+692", "Îles Marshall"),
    ("+850", "Corée du Nord"),
    ("+852", "Hong Kong"),
    ("+853", "Macao"),
    ("+855", "Cambodge"),
    ("+856", "Laos"),
    ("+880", "Bangladesh"),
    ("+886", "Taïwan"),
    ("+960", "Maldives"),
    ("+961", "Liban"),
    ("+962", "Jordanie"),
    ("+963", "Syrie"),
    ("+964", "Irak"),
    ("+965", "Koweït"),
    ("+966", "Arabie saoudite"),
    ("+967", "Yémen"),
    ("+968", "Oman"),
    ("+970", "Palestine"),
    ("+971", "Émirats arabes unis"),
    ("+972", "Israël"),
    ("+973", "Bahreïn"),
    ("+974", "Qatar"),
    ("+975", "Bhoutan"),
    ("+976", "Mongolie"),
    ("+977", "Népal"),
    ("+992", "Tadjikistan"),
    ("+993", "Turkménistan"),
    ("+994", "Azerbaïdjan"),
    ("+995", "Géorgie"),
    ("+996", "Kirghizistan"),
    ("+998", "Ouzbékistan"),
]

# Set des indicatifs valides pour validation rapide
VALID_COUNTRY_CODES = {code for code, _ in COUNTRY_CODES}

# Dictionnaire indicatif -> nom du pays
COUNTRY_CODE_NAMES = {code: name for code, name in COUNTRY_CODES}

# Longueurs minimales et maximales pour les numéros de téléphone (sans indicatif)
MIN_PHONE_LENGTH = 4
MAX_PHONE_LENGTH = 15

# Statuts de messages
MESSAGE_STATUS = {
    "pending": "En attente",
    "sent": "Envoyé",
    "delivered": "Livré",
    "read": "Lu",
    "failed": "Échoué",
}

# Types de messages
MESSAGE_TYPES = {
    "message_1": "Message 1 (Template)",
    "message_2": "Message 2 (Suivi)",
}

# Statuts de campagnes
CAMPAIGN_STATUS = {
    "draft": "Brouillon",
    "sending": "En cours d'envoi",
    "completed": "Terminée",
    "failed": "Échouée",
}

# Types d'interactions
INTERACTION_TYPES = {
    "reply": "Réponse",
    "reaction": "Réaction",
    "read": "Lu",
    "delivered": "Livré",
}

# Rôles utilisateurs
USER_ROLES = {
    "super_admin": "Super Administrateur",
    "admin": "Administrateur",
}

# Limites de pagination
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 100

# Rate limiting WhatsApp
WHATSAPP_RATE_LIMIT = 25  # messages par minute
