// Indicatifs téléphoniques par pays (liste complète mondiale)
export const COUNTRY_CODES = [
  { code: "+93", country: "Afghanistan", flag: "🇦🇫" },
  { code: "+355", country: "Albanie", flag: "🇦🇱" },
  { code: "+213", country: "Algérie", flag: "🇩🇿" },
  { code: "+376", country: "Andorre", flag: "🇦🇩" },
  { code: "+244", country: "Angola", flag: "🇦🇴" },
  { code: "+1268", country: "Antigua-et-Barbuda", flag: "🇦🇬" },
  { code: "+54", country: "Argentine", flag: "🇦🇷" },
  { code: "+374", country: "Arménie", flag: "🇦🇲" },
  { code: "+61", country: "Australie", flag: "🇦🇺" },
  { code: "+43", country: "Autriche", flag: "🇦🇹" },
  { code: "+994", country: "Azerbaïdjan", flag: "🇦🇿" },
  { code: "+1242", country: "Bahamas", flag: "🇧🇸" },
  { code: "+973", country: "Bahreïn", flag: "🇧🇭" },
  { code: "+880", country: "Bangladesh", flag: "🇧🇩" },
  { code: "+1246", country: "Barbade", flag: "🇧🇧" },
  { code: "+375", country: "Biélorussie", flag: "🇧🇾" },
  { code: "+32", country: "Belgique", flag: "🇧🇪" },
  { code: "+501", country: "Belize", flag: "🇧🇿" },
  { code: "+229", country: "Bénin", flag: "🇧🇯" },
  { code: "+975", country: "Bhoutan", flag: "🇧🇹" },
  { code: "+591", country: "Bolivie", flag: "🇧🇴" },
  { code: "+387", country: "Bosnie-Herzégovine", flag: "🇧🇦" },
  { code: "+267", country: "Botswana", flag: "🇧🇼" },
  { code: "+55", country: "Brésil", flag: "🇧🇷" },
  { code: "+673", country: "Brunei", flag: "🇧🇳" },
  { code: "+359", country: "Bulgarie", flag: "🇧🇬" },
  { code: "+226", country: "Burkina Faso", flag: "🇧🇫" },
  { code: "+257", country: "Burundi", flag: "🇧🇮" },
  { code: "+855", country: "Cambodge", flag: "🇰🇭" },
  { code: "+237", country: "Cameroun", flag: "🇨🇲" },
  { code: "+1", country: "Canada", flag: "🇨🇦" },
  { code: "+238", country: "Cap-Vert", flag: "🇨🇻" },
  { code: "+236", country: "Centrafrique", flag: "🇨🇫" },
  { code: "+56", country: "Chili", flag: "🇨🇱" },
  { code: "+86", country: "Chine", flag: "🇨🇳" },
  { code: "+357", country: "Chypre", flag: "🇨🇾" },
  { code: "+57", country: "Colombie", flag: "🇨🇴" },
  { code: "+269", country: "Comores", flag: "🇰🇲" },
  { code: "+242", country: "Congo", flag: "🇨🇬" },
  { code: "+243", country: "RD Congo", flag: "🇨🇩" },
  { code: "+682", country: "Îles Cook", flag: "🇨🇰" },
  { code: "+82", country: "Corée du Sud", flag: "🇰🇷" },
  { code: "+850", country: "Corée du Nord", flag: "🇰🇵" },
  { code: "+506", country: "Costa Rica", flag: "🇨🇷" },
  { code: "+225", country: "Côte d'Ivoire", flag: "🇨🇮" },
  { code: "+385", country: "Croatie", flag: "🇭🇷" },
  { code: "+53", country: "Cuba", flag: "🇨🇺" },
  { code: "+45", country: "Danemark", flag: "🇩🇰" },
  { code: "+253", country: "Djibouti", flag: "🇩🇯" },
  { code: "+1767", country: "Dominique", flag: "🇩🇲" },
  { code: "+20", country: "Égypte", flag: "🇪🇬" },
  { code: "+971", country: "Émirats arabes unis", flag: "🇦🇪" },
  { code: "+593", country: "Équateur", flag: "🇪🇨" },
  { code: "+291", country: "Érythrée", flag: "🇪🇷" },
  { code: "+34", country: "Espagne", flag: "🇪🇸" },
  { code: "+372", country: "Estonie", flag: "🇪🇪" },
  { code: "+268", country: "Eswatini", flag: "🇸🇿" },
  { code: "+1", country: "États-Unis", flag: "🇺🇸" },
  { code: "+251", country: "Éthiopie", flag: "🇪🇹" },
  { code: "+679", country: "Fidji", flag: "🇫🇯" },
  { code: "+358", country: "Finlande", flag: "🇫🇮" },
  { code: "+33", country: "France", flag: "🇫🇷" },
  { code: "+241", country: "Gabon", flag: "🇬🇦" },
  { code: "+220", country: "Gambie", flag: "🇬🇲" },
  { code: "+995", country: "Géorgie", flag: "🇬🇪" },
  { code: "+233", country: "Ghana", flag: "🇬🇭" },
  { code: "+30", country: "Grèce", flag: "🇬🇷" },
  { code: "+1473", country: "Grenade", flag: "🇬🇩" },
  { code: "+590", country: "Guadeloupe", flag: "🇬🇵" },
  { code: "+502", country: "Guatemala", flag: "🇬🇹" },
  { code: "+224", country: "Guinée", flag: "🇬🇳" },
  { code: "+245", country: "Guinée-Bissau", flag: "🇬🇼" },
  { code: "+240", country: "Guinée équatoriale", flag: "🇬🇶" },
  { code: "+592", country: "Guyana", flag: "🇬🇾" },
  { code: "+594", country: "Guyane française", flag: "🇬🇫" },
  { code: "+509", country: "Haïti", flag: "🇭🇹" },
  { code: "+504", country: "Honduras", flag: "🇭🇳" },
  { code: "+852", country: "Hong Kong", flag: "🇭🇰" },
  { code: "+36", country: "Hongrie", flag: "🇭🇺" },
  { code: "+91", country: "Inde", flag: "🇮🇳" },
  { code: "+62", country: "Indonésie", flag: "🇮🇩" },
  { code: "+98", country: "Iran", flag: "🇮🇷" },
  { code: "+964", country: "Irak", flag: "🇮🇶" },
  { code: "+353", country: "Irlande", flag: "🇮🇪" },
  { code: "+354", country: "Islande", flag: "🇮🇸" },
  { code: "+972", country: "Israël", flag: "🇮🇱" },
  { code: "+39", country: "Italie", flag: "🇮🇹" },
  { code: "+1876", country: "Jamaïque", flag: "🇯🇲" },
  { code: "+81", country: "Japon", flag: "🇯🇵" },
  { code: "+962", country: "Jordanie", flag: "🇯🇴" },
  { code: "+7", country: "Kazakhstan", flag: "🇰🇿" },
  { code: "+254", country: "Kenya", flag: "🇰🇪" },
  { code: "+996", country: "Kirghizistan", flag: "🇰🇬" },
  { code: "+686", country: "Kiribati", flag: "🇰🇮" },
  { code: "+965", country: "Koweït", flag: "🇰🇼" },
  { code: "+856", country: "Laos", flag: "🇱🇦" },
  { code: "+266", country: "Lesotho", flag: "🇱🇸" },
  { code: "+371", country: "Lettonie", flag: "🇱🇻" },
  { code: "+961", country: "Liban", flag: "🇱🇧" },
  { code: "+231", country: "Liberia", flag: "🇱🇷" },
  { code: "+218", country: "Libye", flag: "🇱🇾" },
  { code: "+423", country: "Liechtenstein", flag: "🇱🇮" },
  { code: "+370", country: "Lituanie", flag: "🇱🇹" },
  { code: "+352", country: "Luxembourg", flag: "🇱🇺" },
  { code: "+853", country: "Macao", flag: "🇲🇴" },
  { code: "+389", country: "Macédoine du Nord", flag: "🇲🇰" },
  { code: "+261", country: "Madagascar", flag: "🇲🇬" },
  { code: "+60", country: "Malaisie", flag: "🇲🇾" },
  { code: "+265", country: "Malawi", flag: "🇲🇼" },
  { code: "+960", country: "Maldives", flag: "🇲🇻" },
  { code: "+223", country: "Mali", flag: "🇲🇱" },
  { code: "+356", country: "Malte", flag: "🇲🇹" },
  { code: "+212", country: "Maroc", flag: "🇲🇦" },
  { code: "+596", country: "Martinique", flag: "🇲🇶" },
  { code: "+230", country: "Maurice", flag: "🇲🇺" },
  { code: "+222", country: "Mauritanie", flag: "🇲🇷" },
  { code: "+262", country: "Mayotte", flag: "🇾🇹" },
  { code: "+52", country: "Mexique", flag: "🇲🇽" },
  { code: "+691", country: "Micronésie", flag: "🇫🇲" },
  { code: "+373", country: "Moldavie", flag: "🇲🇩" },
  { code: "+377", country: "Monaco", flag: "🇲🇨" },
  { code: "+976", country: "Mongolie", flag: "🇲🇳" },
  { code: "+382", country: "Monténégro", flag: "🇲🇪" },
  { code: "+258", country: "Mozambique", flag: "🇲🇿" },
  { code: "+95", country: "Myanmar", flag: "🇲🇲" },
  { code: "+264", country: "Namibie", flag: "🇳🇦" },
  { code: "+674", country: "Nauru", flag: "🇳🇷" },
  { code: "+977", country: "Népal", flag: "🇳🇵" },
  { code: "+505", country: "Nicaragua", flag: "🇳🇮" },
  { code: "+227", country: "Niger", flag: "🇳🇪" },
  { code: "+234", country: "Nigeria", flag: "🇳🇬" },
  { code: "+47", country: "Norvège", flag: "🇳🇴" },
  { code: "+687", country: "Nouvelle-Calédonie", flag: "🇳🇨" },
  { code: "+64", country: "Nouvelle-Zélande", flag: "🇳🇿" },
  { code: "+968", country: "Oman", flag: "🇴🇲" },
  { code: "+256", country: "Ouganda", flag: "🇺🇬" },
  { code: "+998", country: "Ouzbékistan", flag: "🇺🇿" },
  { code: "+92", country: "Pakistan", flag: "🇵🇰" },
  { code: "+680", country: "Palaos", flag: "🇵🇼" },
  { code: "+970", country: "Palestine", flag: "🇵🇸" },
  { code: "+507", country: "Panama", flag: "🇵🇦" },
  { code: "+675", country: "Papouasie-Nouvelle-Guinée", flag: "🇵🇬" },
  { code: "+595", country: "Paraguay", flag: "🇵🇾" },
  { code: "+31", country: "Pays-Bas", flag: "🇳🇱" },
  { code: "+51", country: "Pérou", flag: "🇵🇪" },
  { code: "+63", country: "Philippines", flag: "🇵🇭" },
  { code: "+48", country: "Pologne", flag: "🇵🇱" },
  { code: "+689", country: "Polynésie française", flag: "🇵🇫" },
  { code: "+351", country: "Portugal", flag: "🇵🇹" },
  { code: "+1787", country: "Porto Rico", flag: "🇵🇷" },
  { code: "+974", country: "Qatar", flag: "🇶🇦" },
  { code: "+262", country: "La Réunion", flag: "🇷🇪" },
  { code: "+40", country: "Roumanie", flag: "🇷🇴" },
  { code: "+44", country: "Royaume-Uni", flag: "🇬🇧" },
  { code: "+7", country: "Russie", flag: "🇷🇺" },
  { code: "+250", country: "Rwanda", flag: "🇷🇼" },
  { code: "+1869", country: "Saint-Kitts-et-Nevis", flag: "🇰🇳" },
  { code: "+1758", country: "Sainte-Lucie", flag: "🇱🇨" },
  { code: "+1784", country: "Saint-Vincent-et-les-Grenadines", flag: "🇻🇨" },
  { code: "+677", country: "Îles Salomon", flag: "🇸🇧" },
  { code: "+503", country: "Salvador", flag: "🇸🇻" },
  { code: "+685", country: "Samoa", flag: "🇼🇸" },
  { code: "+378", country: "Saint-Marin", flag: "🇸🇲" },
  { code: "+239", country: "Sao Tomé-et-Príncipe", flag: "🇸🇹" },
  { code: "+966", country: "Arabie saoudite", flag: "🇸🇦" },
  { code: "+221", country: "Sénégal", flag: "🇸🇳" },
  { code: "+381", country: "Serbie", flag: "🇷🇸" },
  { code: "+248", country: "Seychelles", flag: "🇸🇨" },
  { code: "+232", country: "Sierra Leone", flag: "🇸🇱" },
  { code: "+65", country: "Singapour", flag: "🇸🇬" },
  { code: "+421", country: "Slovaquie", flag: "🇸🇰" },
  { code: "+386", country: "Slovénie", flag: "🇸🇮" },
  { code: "+252", country: "Somalie", flag: "🇸🇴" },
  { code: "+249", country: "Soudan", flag: "🇸🇩" },
  { code: "+211", country: "Soudan du Sud", flag: "🇸🇸" },
  { code: "+94", country: "Sri Lanka", flag: "🇱🇰" },
  { code: "+46", country: "Suède", flag: "🇸🇪" },
  { code: "+41", country: "Suisse", flag: "🇨🇭" },
  { code: "+597", country: "Suriname", flag: "🇸🇷" },
  { code: "+963", country: "Syrie", flag: "🇸🇾" },
  { code: "+992", country: "Tadjikistan", flag: "🇹🇯" },
  { code: "+886", country: "Taïwan", flag: "🇹🇼" },
  { code: "+255", country: "Tanzanie", flag: "🇹🇿" },
  { code: "+235", country: "Tchad", flag: "🇹🇩" },
  { code: "+420", country: "Tchéquie", flag: "🇨🇿" },
  { code: "+66", country: "Thaïlande", flag: "🇹🇭" },
  { code: "+670", country: "Timor oriental", flag: "🇹🇱" },
  { code: "+228", country: "Togo", flag: "🇹🇬" },
  { code: "+676", country: "Tonga", flag: "🇹🇴" },
  { code: "+1868", country: "Trinité-et-Tobago", flag: "🇹🇹" },
  { code: "+216", country: "Tunisie", flag: "🇹🇳" },
  { code: "+993", country: "Turkménistan", flag: "🇹🇲" },
  { code: "+90", country: "Turquie", flag: "🇹🇷" },
  { code: "+688", country: "Tuvalu", flag: "🇹🇻" },
  { code: "+380", country: "Ukraine", flag: "🇺🇦" },
  { code: "+598", country: "Uruguay", flag: "🇺🇾" },
  { code: "+678", country: "Vanuatu", flag: "🇻🇺" },
  { code: "+379", country: "Vatican", flag: "🇻🇦" },
  { code: "+58", country: "Venezuela", flag: "🇻🇪" },
  { code: "+84", country: "Viêt Nam", flag: "🇻🇳" },
  { code: "+967", country: "Yémen", flag: "🇾🇪" },
  { code: "+260", country: "Zambie", flag: "🇿🇲" },
  { code: "+263", country: "Zimbabwe", flag: "🇿🇼" },
] as const;

// Statuts des messages
export const MESSAGE_STATUS = {
  PENDING: "pending",
  SENT: "sent",
  DELIVERED: "delivered",
  READ: "read",
  FAILED: "failed",
} as const;

// Statuts des campagnes
export const CAMPAIGN_STATUS = {
  DRAFT: "draft",
  SENDING: "sending",
  COMPLETED: "completed",
  FAILED: "failed",
} as const;

// Rôles utilisateurs
export const USER_ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
} as const;

// Configuration de pagination
export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 50,
  MAX_PAGE_SIZE: 100,
} as const;

// Types d'interactions
export const INTERACTION_TYPES = {
  REPLY: "reply",
  REACTION: "reaction",
  READ: "read",
  DELIVERED: "delivered",
} as const;

// Couleurs pour les catégories (gradients)
export const CATEGORY_GRADIENTS = [
  "from-blue-500 to-cyan-500",
  "from-purple-500 to-pink-500",
  "from-green-500 to-emerald-500",
  "from-orange-500 to-amber-500",
  "from-red-500 to-rose-500",
  "from-indigo-500 to-violet-500",
  "from-teal-500 to-green-500",
  "from-fuchsia-500 to-purple-500",
] as const;

// Fonction pour obtenir un gradient aléatoire
export function getRandomGradient(): string {
  const index = Math.floor(Math.random() * CATEGORY_GRADIENTS.length);
  return CATEGORY_GRADIENTS[index];
}

// Fonction pour formater un indicatif pays
export function formatCountryCode(code: string): string {
  const country = COUNTRY_CODES.find((c) => c.code === code);
  return country ? `${country.flag} ${country.code} ${country.country}` : code;
}
